services:
  getnewsapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: getnewsapi
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      TZ: Europe/Belgrade
    ports:
      - "5001:5000"
    volumes:
      - ./GetNewsAPI:/app
    restart: unless-stopped
    command: python app.py
